on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        description: Choose version bump
        options:
        - major
        - minor

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: main
    - name: Build & Test
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Clean install of dependencies
      run: npm ci
    - name: Build application
      run: npm run build --if-present
    - name: Run test
      run: npm run test:prod

  update-version:
    needs: build-test

    runs-on: ubuntu-latest

    outputs:
      version: ${{ env.APP_VERSION }}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
    - name: Build & Test
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Set up config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
    - name: Update major version
      if: (github.event.inputs.version == 'major')
      run: npm version premajor --preid="rc" -m "Upgrade to %s"
    - name: Update minor version
      if: (github.event.inputs.version == 'minor')
      run: npm version preminor --preid="rc" -m "Upgrade to %s"
    - name: Parse version
      run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    - name: Create release branch
      run: git push origin main:release/$(echo ${{ env.APP_VERSION }} | cut -d- -f1) --follow-tags

  create-release:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.update-version.outputs.version }}
          release_name: Release ${{ needs.update-version.outputs.version }}
          body: |
            Release ${{ needs.update-version.outputs.version }}
          draft: false
          prerelease: true
      - name: Deploy to TEST
        run: echo "Successfully deployed to TEST-Environment."
